//! OpenAI-compatible API request and response types.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Common
// ---------------------------------------------------------------------------

/// Role of a participant in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System prompt that sets context for the conversation.
    System,
    /// Message authored by the human user.
    User,
    /// Message generated by the AI assistant.
    Assistant,
    /// Tool result message returned after a tool call.
    Tool,
}

/// A single message in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Participant role.
    pub role: Role,
    /// Text content of the message (may be absent for pure tool-call messages).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Tool calls initiated by the assistant in this turn.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// For `role: tool` messages, identifies which tool call this is the result of.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Optional name (used in older function-calling spec).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ChatMessage {
    /// Convenience constructor for a plain user or system message.
    pub fn text(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Tool / function calling
// ---------------------------------------------------------------------------

/// An assistant-initiated call to a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this specific call (used to correlate tool results).
    #[serde(default)]
    pub id: String,
    /// Always `"function"` in the current spec.
    #[serde(rename = "type", default)]
    pub kind: String,
    /// The function being invoked.
    pub function: FunctionCall,
    /// Zero-based index in the tool_calls array (present in streaming chunks).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub index: Option<u32>,
}

/// The function name and arguments from a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// Name of the function.
    #[serde(default)]
    pub name: String,
    /// JSON-encoded arguments string.
    #[serde(default)]
    pub arguments: String,
}

/// A tool available to the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    /// Always `"function"` for function-calling tools.
    #[serde(rename = "type")]
    pub kind: String,
    /// Schema of the callable function.
    pub function: FunctionDefinition,
}

impl Tool {
    /// Convenience constructor for a function tool.
    pub fn function(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters: serde_json::Value,
    ) -> Self {
        Self {
            kind: "function".into(),
            function: FunctionDefinition {
                name: name.into(),
                description: Some(description.into()),
                parameters: Some(parameters),
            },
        }
    }
}

/// JSON-schema description of a callable function.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionDefinition {
    /// Name of the function.
    pub name: String,
    /// Human-readable description shown to the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// JSON Schema object describing the function's parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

// ---------------------------------------------------------------------------
// Non-streaming request / response
// ---------------------------------------------------------------------------

/// Request body for `/v1/chat/completions`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionRequest {
    /// Model identifier, e.g. `"gpt-4o"` or `"ai/mistral-nemo"`.
    pub model: String,
    /// Conversation history.
    pub messages: Vec<ChatMessage>,
    /// Tools the model may call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    /// Controls which tool (if any) the model must call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<serde_json::Value>,
    /// Maximum tokens to generate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Sampling temperature (0–2).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// Request token-level log probabilities when supported.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<bool>,
    /// Whether to stream the response.  Set by the client when streaming.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
}

impl ChatCompletionRequest {
    /// Minimal constructor for a simple conversation.
    pub fn new(model: impl Into<String>, messages: Vec<ChatMessage>) -> Self {
        Self {
            model: model.into(),
            messages,
            tools: None,
            tool_choice: None,
            max_tokens: None,
            temperature: None,
            logprobs: None,
            stream: None,
        }
    }
}

/// Successful response from `/v1/chat/completions` (non-streaming).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponse {
    /// Unique completion identifier.
    pub id: String,
    /// Object type, always `"chat.completion"`.
    pub object: String,
    /// Unix timestamp of when the completion was created.
    pub created: u64,
    /// Model that generated this completion.
    pub model: String,
    /// List of generated completion candidates.
    pub choices: Vec<Choice>,
    /// Token usage statistics, if provided by the API.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

/// One completion candidate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Choice {
    /// Zero-based index of this choice in the `choices` array.
    pub index: u32,
    /// The generated message.
    pub message: ChatMessage,
    /// Token-level log probability data (if requested).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<LogProbs>,
    /// Reason the model stopped generating (`"stop"`, `"length"`, `"tool_calls"`, etc.).
    pub finish_reason: Option<String>,
}

/// Token-level log probability info for a completion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogProbs {
    /// Logprobs for generated content tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<Vec<TokenLogProb>>,
}

/// Log probability for a single token.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenLogProb {
    /// Log probability of the token (natural log).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logprob: Option<f64>,
}

/// Token-usage statistics returned by the API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Tokens consumed by the prompt (including any injected system messages).
    pub prompt_tokens: u32,
    /// Tokens generated in the completion.
    pub completion_tokens: u32,
    /// Sum of `prompt_tokens` and `completion_tokens`.
    pub total_tokens: u32,
}

// ---------------------------------------------------------------------------
// Streaming types (SSE)
// ---------------------------------------------------------------------------

/// A single chunk from a streaming `/v1/chat/completions` response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionChunk {
    /// Unique identifier shared across all chunks for the same completion.
    pub id: String,
    /// Object type, always `"chat.completion.chunk"`.
    pub object: String,
    /// Unix timestamp of when the completion was created.
    pub created: u64,
    /// Model that generated this chunk.
    pub model: String,
    /// List of delta choices in this chunk.
    pub choices: Vec<ChunkChoice>,
}

/// Delta choice inside a streaming chunk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkChoice {
    /// Zero-based index of this choice in the `choices` array.
    pub index: u32,
    /// Incremental delta for this chunk.
    pub delta: DeltaMessage,
    /// Reason the model stopped, present only in the final chunk (`"stop"`, `"length"`, etc.).
    pub finish_reason: Option<String>,
}

/// Partial message content sent in a streaming chunk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeltaMessage {
    /// Role, included only in the first chunk.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// Content fragment (may be empty string or absent).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Tool-call fragments (streamed incrementally).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // ── Role ─────────────────────────────────────────────────────────────────

    #[test]
    fn role_serde_roundtrip() {
        for role in [Role::System, Role::User, Role::Assistant, Role::Tool] {
            let json = serde_json::to_string(&role).unwrap();
            let decoded: Role = serde_json::from_str(&json).unwrap();
            assert_eq!(decoded, role);
        }
    }

    #[test]
    fn role_serializes_as_lowercase() {
        assert_eq!(serde_json::to_string(&Role::User).unwrap(), "\"user\"");
        assert_eq!(
            serde_json::to_string(&Role::Assistant).unwrap(),
            "\"assistant\""
        );
        assert_eq!(serde_json::to_string(&Role::System).unwrap(), "\"system\"");
        assert_eq!(serde_json::to_string(&Role::Tool).unwrap(), "\"tool\"");
    }

    // ── ChatMessage ───────────────────────────────────────────────────────────

    #[test]
    fn chat_message_text_constructor() {
        let msg = ChatMessage::text(Role::User, "Hello");
        assert_eq!(msg.role, Role::User);
        assert_eq!(msg.content.as_deref(), Some("Hello"));
        assert!(msg.tool_calls.is_none());
        assert!(msg.tool_call_id.is_none());
        assert!(msg.name.is_none());
    }

    #[test]
    fn chat_message_skips_none_fields_in_serialization() {
        let msg = ChatMessage::text(Role::User, "Hello");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("tool_calls"));
        assert!(!json.contains("tool_call_id"));
        assert!(!json.contains("\"name\""));
    }

    #[test]
    fn chat_message_serde_roundtrip_with_all_fields() {
        let msg = ChatMessage {
            role: Role::Tool,
            content: Some("result".into()),
            tool_calls: None,
            tool_call_id: Some("call-1".into()),
            name: Some("my_tool".into()),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let decoded: ChatMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.tool_call_id.as_deref(), Some("call-1"));
        assert_eq!(decoded.name.as_deref(), Some("my_tool"));
    }

    // ── Tool / FunctionDefinition ─────────────────────────────────────────────

    #[test]
    fn tool_function_constructor() {
        let schema = json!({"type": "object", "properties": {"city": {"type": "string"}}});
        let tool = Tool::function("get_weather", "Get weather for a city", schema.clone());
        assert_eq!(tool.kind, "function");
        assert_eq!(tool.function.name, "get_weather");
        assert_eq!(
            tool.function.description.as_deref(),
            Some("Get weather for a city")
        );
        assert_eq!(tool.function.parameters.as_ref().unwrap()["type"], "object");
    }

    #[test]
    fn tool_serde_roundtrip() {
        let tool = Tool::function(
            "search",
            "Search the web",
            json!({"type": "object", "properties": {}}),
        );
        let json = serde_json::to_string(&tool).unwrap();
        let decoded: Tool = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.function.name, "search");
    }

    // ── ChatCompletionRequest ─────────────────────────────────────────────────

    #[test]
    fn chat_completion_request_new() {
        let req = ChatCompletionRequest::new("gpt-4o", vec![ChatMessage::text(Role::User, "hi")]);
        assert_eq!(req.model, "gpt-4o");
        assert_eq!(req.messages.len(), 1);
        assert!(req.tools.is_none());
        assert!(req.temperature.is_none());
        assert!(req.stream.is_none());
    }

    #[test]
    fn chat_completion_request_serde_skips_none_fields() {
        let req = ChatCompletionRequest::new("gpt-4o", vec![ChatMessage::text(Role::User, "hi")]);
        let json = serde_json::to_string(&req).unwrap();
        assert!(!json.contains("\"tools\""));
        assert!(!json.contains("\"stream\""));
        assert!(!json.contains("\"temperature\""));
    }

    // ── ChatCompletionResponse / Choice / Usage ───────────────────────────────

    #[test]
    fn chat_completion_response_serde_roundtrip() {
        let resp_json = json!({
            "id": "cmpl-1",
            "object": "chat.completion",
            "created": 1700000000u64,
            "model": "gpt-4o",
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": "Hello!"},
                "finish_reason": "stop"
            }],
            "usage": {"prompt_tokens": 5, "completion_tokens": 3, "total_tokens": 8}
        });
        let resp: ChatCompletionResponse = serde_json::from_value(resp_json).unwrap();
        assert_eq!(resp.id, "cmpl-1");
        assert_eq!(resp.choices[0].message.content.as_deref(), Some("Hello!"));
        let usage = resp.usage.as_ref().unwrap();
        assert_eq!(usage.total_tokens, 8);
    }

    // ── Streaming types ───────────────────────────────────────────────────────

    #[test]
    fn chat_completion_chunk_serde_roundtrip() {
        let chunk_json = json!({
            "id": "c1",
            "object": "chat.completion.chunk",
            "created": 1700000000u64,
            "model": "gpt-4o",
            "choices": [{
                "index": 0,
                "delta": {"role": "assistant", "content": "Hi"},
                "finish_reason": null
            }]
        });
        let chunk: ChatCompletionChunk = serde_json::from_value(chunk_json).unwrap();
        assert_eq!(chunk.id, "c1");
        assert_eq!(chunk.choices[0].delta.content.as_deref(), Some("Hi"));
        assert_eq!(chunk.choices[0].delta.role, Some(Role::Assistant));
    }
}
