name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    continue-on-error: true
    uses: plures/.github/.github/workflows/dependabot-auto-merge.yml@main
    secrets: inherit
